"""
Data ingestion pipeline for the Corporate Carbon Footprint Predictor.

Supports three data sources with automatic CSV-fallback:

1. **CDP Open Data** – Scope 1 & 2 emissions by company
2. **Yahoo Finance** – Financial fundamentals via ``yfinance``
3. **World Bank** – Country-level macro indicators via ``wbgapi``

If live APIs are unavailable the module falls back to pre-cached CSVs
or, as a last resort, to synthetic data generated by
:mod:`src.synthetic_data`.

Usage::

    python -m src.ingestion            # runs full pipeline
    python -m src.ingestion --synthetic # force synthetic data
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config as cfg
from src.utils import get_logger, save_csv, load_csv

logger = get_logger(__name__)


# ══════════════════════════════════════════════
#  1. CDP Emissions loader
# ══════════════════════════════════════════════

class CDPIngestion:
    """Load and validate CDP emissions data from a CSV export.

    Expected schema (minimum)::

        company_name, reporting_year, scope1_emissions, scope2_emissions,
        country, sector, [industry]

    If the file is missing the module can generate synthetic data
    transparently.
    """

    REQUIRED_COLS = [
        "company_name",
        "reporting_year",
        cfg.TARGET_SCOPE1,
        cfg.TARGET_SCOPE2,
    ]

    def __init__(self, path: Optional[Path] = None) -> None:
        self.path = path or cfg.RAW_EMISSIONS_FILE

    def load(self) -> pd.DataFrame:
        """Load emissions data; fall back to synthetic if file missing.

        Returns:
            DataFrame with validated schema.
        """
        if self.path.exists():
            logger.info("Loading CDP data from %s", self.path)
            df = load_csv(self.path)
        else:
            logger.warning(
                "CDP file not found at %s – generating synthetic data",
                self.path,
            )
            from src.synthetic_data import generate_synthetic_dataset
            df, country_df = generate_synthetic_dataset()
            save_csv(df, self.path)
            save_csv(country_df, cfg.RAW_WORLDBANK_FILE)

        self._validate(df)
        return df

    def _validate(self, df: pd.DataFrame) -> None:
        """Check required columns are present."""
        missing = set(self.REQUIRED_COLS) - set(df.columns)
        if missing:
            raise ValueError(f"CDP data missing columns: {sorted(missing)}")
        logger.info(
            "CDP data validated: %d records, years %s–%s",
            len(df),
            df["reporting_year"].min(),
            df["reporting_year"].max(),
        )


# ══════════════════════════════════════════════
#  2. Yahoo Finance loader
# ══════════════════════════════════════════════

class YahooFinanceIngestion:
    """Fetch financial fundamentals for a list of tickers.

    Attempts live ``yfinance`` calls first; falls back to cached CSV.
    """

    CACHE_FILE = cfg.RAW_FINANCIALS_FILE

    def load(
        self,
        tickers: Optional[list[str]] = None,
        force_cache: bool = False,
    ) -> pd.DataFrame:
        """Return financials DataFrame.

        Args:
            tickers: List of ticker symbols to look up.
            force_cache: Skip API and use cached CSV.

        Returns:
            DataFrame with ticker, revenue, total_assets, etc.
        """
        if force_cache or tickers is None:
            return self._load_from_cache()

        try:
            return self._fetch_live(tickers)
        except Exception as exc:
            logger.warning("yfinance API failed (%s) – using cache", exc)
            return self._load_from_cache()

    def _fetch_live(self, tickers: list[str]) -> pd.DataFrame:
        """Fetch from Yahoo Finance API."""
        import yfinance as yf

        logger.info("Fetching Yahoo Finance data for %d tickers …", len(tickers))
        records = []
        for ticker_sym in tickers:
            try:
                tk = yf.Ticker(ticker_sym)
                info = tk.info
                records.append({
                    "ticker": ticker_sym,
                    "revenue": info.get("totalRevenue"),
                    "total_assets": info.get("totalAssets"),
                    "market_cap": info.get("marketCap"),
                    "employee_count": info.get("fullTimeEmployees"),
                    "sector": info.get("sector"),
                    "industry": info.get("industry"),
                    "country": info.get("country"),
                })
            except Exception as e:
                logger.warning("Failed to fetch %s: %s", ticker_sym, e)

        df = pd.DataFrame(records)
        if not df.empty:
            save_csv(df, self.CACHE_FILE)
        return df

    def _load_from_cache(self) -> pd.DataFrame:
        """Load from CSV cache."""
        if self.CACHE_FILE.exists():
            logger.info("Loading cached Yahoo Finance data")
            return load_csv(self.CACHE_FILE)
        logger.warning("No Yahoo Finance cache found – returning empty DataFrame")
        return pd.DataFrame()


# ══════════════════════════════════════════════
#  3. World Bank macro indicators
# ══════════════════════════════════════════════

class WorldBankIngestion:
    """Load country-level economic indicators.

    Tries the ``wbgapi`` library first; falls back to cached CSV.
    """

    INDICATORS = {
        "NY.GDP.PCAP.CD": "gdp_per_capita",
        "EG.USE.PCAP.KG.OE": "energy_intensity",
    }

    CACHE_FILE = cfg.RAW_WORLDBANK_FILE

    def load(self, force_cache: bool = False) -> pd.DataFrame:
        """Return country-level DataFrame.

        Args:
            force_cache: Skip API and use cached CSV.

        Returns:
            DataFrame with country (ISO-3), gdp_per_capita,
            energy_intensity.
        """
        if force_cache:
            return self._load_from_cache()

        try:
            return self._fetch_live()
        except Exception as exc:
            logger.warning("World Bank API failed (%s) – using cache", exc)
            return self._load_from_cache()

    def _fetch_live(self) -> pd.DataFrame:
        """Fetch from World Bank API."""
        import wbgapi as wb

        logger.info("Fetching World Bank indicators …")
        frames = []
        for ind_code, col_name in self.INDICATORS.items():
            try:
                data = wb.data.DataFrame(ind_code, mrv=1)
                data = data.reset_index()
                data.columns = ["country", col_name]
                frames.append(data)
            except Exception as e:
                logger.warning("Indicator %s failed: %s", ind_code, e)

        if frames:
            df = frames[0]
            for f in frames[1:]:
                df = df.merge(f, on="country", how="outer")
            save_csv(df, self.CACHE_FILE)
            return df

        return self._load_from_cache()

    def _load_from_cache(self) -> pd.DataFrame:
        """Load from CSV cache."""
        if self.CACHE_FILE.exists():
            logger.info("Loading cached World Bank data")
            return load_csv(self.CACHE_FILE)
        logger.warning(
            "No World Bank cache found – returning empty DataFrame"
        )
        return pd.DataFrame()


# ══════════════════════════════════════════════
#  4. Merge all sources
# ══════════════════════════════════════════════

def merge_all_sources(
    emissions_df: pd.DataFrame,
    financials_df: pd.DataFrame,
    worldbank_df: pd.DataFrame,
) -> pd.DataFrame:
    """Left-join emissions ← financials ← world-bank on shared keys.

    When columns overlap (e.g. both emissions and financials have
    ``revenue``), the emissions source is preferred and the financials
    column is used only to fill NaNs.

    Args:
        emissions_df: CDP emissions DataFrame (primary).
        financials_df: Yahoo Finance financials DataFrame.
        worldbank_df: World Bank country indicators.

    Returns:
        Merged DataFrame saved to ``MERGED_RAW_FILE``.
    """
    logger.info(
        "Merging sources: emissions=%d, financials=%d, worldbank=%d",
        len(emissions_df), len(financials_df), len(worldbank_df),
    )

    df = emissions_df.copy()

    # Merge financials on ticker (if both have ticker column)
    if not financials_df.empty and "ticker" in financials_df.columns:
        overlap = set(df.columns) & set(financials_df.columns) - {"ticker"}
        fin_cols = [c for c in financials_df.columns if c not in overlap]
        df = df.merge(financials_df[fin_cols], on="ticker", how="left")

    # Merge country-level indicators
    if not worldbank_df.empty and "country" in worldbank_df.columns:
        df = df.merge(worldbank_df, on="country", how="left")

    logger.info("Merged dataset: %d rows × %d columns", *df.shape)
    save_csv(df, cfg.MERGED_RAW_FILE)
    return df


# ══════════════════════════════════════════════
#  CLI
# ══════════════════════════════════════════════

def run_ingestion(use_synthetic: bool = False) -> pd.DataFrame:
    """Execute the full ingestion pipeline.

    Args:
        use_synthetic: If True, skip API calls and use synthetic data.

    Returns:
        Merged raw DataFrame.
    """
    if use_synthetic:
        logger.info("── Using synthetic data ──")
        from src.synthetic_data import generate_synthetic_dataset
        emissions_df, country_df = generate_synthetic_dataset()
        save_csv(emissions_df, cfg.RAW_EMISSIONS_FILE)
        save_csv(country_df, cfg.RAW_WORLDBANK_FILE)
        financials_df = pd.DataFrame()
    else:
        emissions_df = CDPIngestion().load()
        financials_df = YahooFinanceIngestion().load(force_cache=True)
        country_df = WorldBankIngestion().load(force_cache=True)

    merged = merge_all_sources(emissions_df, financials_df, country_df)
    return merged


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Run data ingestion pipeline")
    parser.add_argument(
        "--synthetic", action="store_true",
        help="Use synthetic data instead of live APIs",
    )
    args = parser.parse_args()
    run_ingestion(use_synthetic=args.synthetic)


if __name__ == "__main__":
    main()
